### ISSUE TITLE
Where is this going?

### ISSUE THREAD

**Issue by MichaelMartinez** [kennethreitz/records#4]
Just curious about the plan for this library going forward:

1. Do you want this to be an ORM built on top of psycopg2?
2. Do you want to add more database drivers?
3. Do you want this to become an ORM for multiple databases or just Postgres?
4. Are you waiting to see where the community takes it? :smile: 

Sending :heart_eyes: for Requests!!! Maybe this turns into something like along those lines?

**Comment by kennethreitz** [comment]
1. No, I don't think so. I was playing for a while with trying to have auto-loaded SQLAlchemy tables built in, but I decided that that's another project for another day :)
2. I'm not sure. My gut instinct says no, since Postgres is the best anyway :)
3. See #2.
4. Absolutely!

Thanks for the :heart_eyes:! I'd love for this to turn into something along those lines. When I first started and released Requests it was a very similar project. I was just trying to solve a simple problem that I often had, and I was very surprised by the interest others took in it, and where contributions (especially early on) took the project in the direction it is today. So, I guess we'll see :)

**Comment by MichaelMartinez** [comment]
Thank you for the response! 

So, there will be lots of requests for other db drivers. Your first few issues are dealing with that already. I am not sure how to abstract, let alone integrate psycopg2, to an agnostic driver (or multiple drivers) with the code as it stands now. In my mind, doing this would just reimplement SQLalchemy... 

Perhaps, just let it ride as a Postgres thing and see what is missing from there. Make that bomb proof and extend. I have too much impostor syndrome to really offer more.

**Comment by kennethreitz** [comment]
Well, we could use SQLAlchemy's low-level APIs to support many database types, while keeping the interface identical.

**Comment by MichaelMartinez** [comment]
I am definitely game to give "something" a shot. If nothing else, perhaps I can try to implement [SQLite #5](https://github.com/kennethreitz/records/issues/5) to see how it fits in with the current code. This may yield some ideas for SQLalchemy and get me up to speed with DB stuff in general.

**Comment by kennethreitz** [comment]
Holding off on this, for now. SQLAlchemy's parameterization support is slightly different, and requires queries that contain `%` to fail. Ideally, I'd like exact queries to work as expected, without modification.
