### ISSUE TITLE
Support for Executing Multiple Statements

### ISSUE THREAD

**Issue by kevgathuku** [kennethreitz/records#76]
Hi, 
I am trying to use the records query interface on small project, but sadly it lacks support for executing multiple statements. 
I am encountering this when trying to run SQL already stored in a file.
For example, when trying to run the following SQL for creating tables:

``` sql
CREATE TABLE IF NOT EXISTS "rooms" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "name" TEXT UNIQUE,
    "type" TEXT
);
CREATE TABLE IF NOT EXISTS "people" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "name" TEXT,
    "accomodation" TEXT
);
```

Trying to run `db.query_file('queries/create-tables.sql')` fails with the following error:

```
sqlite3.Warning: You can only execute one statement at a time.
```

Is there a way to get support for executing such multiple statements at once?
Thanks for creating this package.

**Comment by TomFaulkner** [comment]
I know this issue is 4 months old now, but I am having a similar issue, though not trying to run the query from a file.

I have a statement that is used to create a row id that runs before the select statement, something along the lines of this following:
set @row_num = 0;
SELECT @row_num:=@row_num + 1 AS ID,

**Comment by vlcinsky** [comment]
Testing with latest `records` (from github) I see, the sql file works now well (I see new tables created in th database and no complains).

Closing.
